apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appname }}-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageclassname }}
  capacity:
    storage: {{ .Values.volumestorage }}
  accessModes:
    - {{ .Values.volumesaccessmodes }}
  hostPath:
    path: {{ .Values.volumepath }}
