apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appname }}-pv-claim
spec:
  storageClassName: {{ .Values.storageclassname }}
  accessModes:
    - {{ .Values.storageaccessmodes }}
  resources:
    requests:
      storage: {{ .Values.volumestorage }}
