apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: {{ .Values.appname }}
  #clusterIP: None
