apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-tls
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certificate }}
  tls.key: {{ .Values.key }}
